sudo: false
language: java
jdk: oraclejdk8
services:
- docker
cache:
  directories:
  - "$HOME/.cache"

deploy:
  provider: packagecloud
  repository: "muzyczna-studnia"
  username: "mateodziej"
  token: $PACKAGECLOUD_TOKEN
  skip_cleanup: true
  on:
    all_branches: true
    tags: true